stages:
  - lint
  - build
  - quality

variables:
  LE_FQDN: "ci.dev.acuparse.com"
  EMAIL: "ci@dev.acuparse.com"
  TEST_USERNAME: "ci"
  TEST_PASSWORD: ":}P@sssW0rd:)"

.build_template: &build_template
  stage: build
  before_script:
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install curl wget -y
  script:
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then bash install -b dev -s -d -e -l ""$LE_FQDN","$EMAIL",n,n"; else bash install -s -d; fi
    - export $(cat ~/.acuparse_db)
    - curl -d 'mysql[hostname]=localhost&mysql[database]=acuparse&mysql[username]=acuparse&mysql[password]='"$ACUPARSE_DATABASE_PASSWORD"'&mysql[trim]=1' -X POST 'http://localhost/admin/install/?database'
    - curl -d 'username='"$TEST_USERNAME"'&email='"$EMAIL"'&password='"$TEST_PASSWORD" -X POST 'http://127.0.0.1/admin/install/?account&do'
    - curl -o index.html http://127.0.0.1
    - curl -k -o index_ssl.html https://127.0.0.1
    - curl -o output.json http://127.0.0.1/?json
    - curl -o weather.html http://127.0.0.1/?weather
    - curl -o archive.html http://127.0.0.1/archive?html
  artifacts:
    untracked: true

bash_scripts:
  image: koalaman/shellcheck-alpine
  stage: lint
  before_script:
    - export SHELLCHECK_OPTS="-e SC2034 -e SC2059"
  script:
    - shellcheck install
    - shellcheck resources/*

markdown:
  stage: lint
  image: node:latest
  before_script:
    - npm install -g markdownlint-cli
  script:
    - markdownlint .

debian_buster:
  image: debian:buster
  <<: *build_template

ubuntu_bionic:
  image: ubuntu:bionic
  <<: *build_template
ubuntu_focal:
  image: ubuntu:focal
  <<: *build_template

code_quality:
  stage: quality
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - docker run
      --env SOURCE_CODE="$PWD"
      --volume "$PWD":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      "registry.gitlab.com/gitlab-org/security-products/codequality:12-0-stable" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  only:
    - branches
    - tags
  except:
    variables:
      - $CODE_QUALITY_DISABLED
