#!/usr/bin/env bash

##
# Acuparse Debian Buster to Bullseye Script
# @copyright Copyright (C) 2015-2024 Maxwell Power
# @author Maxwell Power <max@acuparse.com>
# @license MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
##

if [[ $(id -u) != "0" ]]; then
  echo "Sorry, you are not root."
  exit 1
fi
BOLD_GREEN_TEXT='\033[1;32m'
RED_TEXT='\033[0;31m'
RESET_TEXT='\033[0m'

printf "\n${BOLD_GREEN_TEXT}#######################\n# Installation Ready! #\n#######################${RESET_TEXT}\n\n"
printf "This process will upgrade Debian Buster to Bullseye.\nThis is your last chance to exit.\n\n"
printf "${RED_TEXT}When ready, Press [ENTER] to continue${RESET_TEXT}\n"
read -r READY

printf "Updating Before Upgrade\n\n"
apt-get update
apt-get dist-upgrade -y

printf "Updating Sources from Buster to Bullseye\n\n"
sed -i 's/buster/bullseye/g' /etc/apt/sources.list
sed -i 's#deb http://security.debian.org/ bullseye/updates#deb https://security.debian.org/debian-security bullseye-security#g' /etc/apt/sources.list
sed -i 's#deb-src http://security.debian.org/ bullseye/updates#deb-src https://security.debian.org/debian-security bullseye-security#g' /etc/apt/sources.list

printf "Removing PHP Sources\n\n"
rm /etc/apt/sources.list.d/php.list || echo "No PHP Sources"

printf "Begin Upgrade to Bullseye\n\n"
apt-get update
apt-get dist-upgrade -y

printf "Upgrading PHP to 7.4\n\n"
printf "Removing PHP 5\n\n"
apt-get remove php5* -y || echo "No PHP 5"
a2dismod php5

printf "Removing PHP 7.0\n\n"
apt-get remove php7.0* -y || echo "No PHP 7.0"
a2dismod php7.0

printf "Removing PHP 7.1\n\n"
apt-get remove php7.1* -y || echo "No PHP 7.1"
a2dismod php7.1

printf "Removing PHP 7.2\n\n"
apt-get remove php7.2* -y  || echo "No PHP 7.2"
a2dismod php7.2

printf "Removing PHP 7.3\n\n"
apt-get remove php7.3* -y || echo "No PHP 7.3"
a2dismod php7.3

apt-get update
apt-get install git dnsutils imagemagick apache2 default-mysql-server php7.4 libapache2-mod-php7.4 php7.4-mysql php7.4-gd php7.4-curl php7.4-json php7.4-cli php7.4-common -y
a2enmod php7.4

printf "\nCleanup APT\n\n"
apt-get autoremove -y
apt-get purge
apt-get clean

printf "\nCleanup NTP\n\n"
apt-get purge ntp -y
systemctl enable systemd-timesyncd
systemctl start systemd-timesyncd
timedatectl set-ntp on

printf "\nUpdate Apache SSL Config\n\n"
sed -i 's/SSLEngine on/SSLEngine on\n        SSLProtocol all +TLSv1.1 -SSLv3\n        SSLCipherSuite ALL:@SECLEVEL=1/' /etc/apache2/sites-available/acuparse-ssl.conf

printf "\nRestarting Apache\n\n"
systemctl restart apache2

printf "\nDONE! System Reboot Required!\n"
exit 0
