#!/usr/bin/env bash

##
# Acuparse Installation Script
# Let's Encrypt Installer
# @copyright Copyright (C) 2015-2019 Maxwell Power
# @author Maxwell Power <max@acuparse.com>
# @license MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
##

DIST=$(cat /etc/*release | grep '^ID=' | awk -F=  '{ print $2 }')
DEB_VERSION=$(cat /etc/*release | grep '^VERSION_ID=' | awk -F=  '{ print $2 }')
UBU_VERSION=$(cat /etc/*release | grep '^DISTRIB_RELEASE=' | awk -F='  { print $2 }')

if [[ $(id -u) != "0" ]]; then
    echo "Sorry, you are not root."
    exit 1
fi

install_le_cert () {
    if [[ ("$LE_SECURE_WWW" = "y") || ("$LE_SECURE_WWW" = "Y") ]]; then
        LE_SECURE_DOMAINS=(-d "$LE_FQDN" -d www."$LE_FQDN")
    else
        LE_SECURE_DOMAINS=(-d "$LE_FQDN")
    fi

    if [[ ("$LE_REDIRECT_ENABLED" = "y") || ("$LE_REDIRECT_ENABLED" = "Y") ]]; then
        LE_REDIRECT="redirect"
    else
        LE_REDIRECT="no-redirect"
    fi
    if [[ ("$DIST" = "ubuntu") && ("$UBU_VERSION" = "18.04") ]]; then
        printf "UBUNTU 18.04 DETECTED! Using certbot PPA\n"
        apt-get install software-properties-common -y
        add-apt-repository ppa:certbot/certbot -y
        apt-get update > /dev/null 2>&1
    fi
    apt-get install python-certbot-apache -y
    a2dissite 000-default.conf > /dev/null 2>&1
    a2dissite acuparse.conf > /dev/null 2>&1
    rm /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/default-ssl.conf  /etc/apache2/sites-enabled/acuparse.conf > /dev/null 2>&1
    cp /opt/acuparse/config/acuparse.conf /etc/apache2/sites-available/ > /dev/null 2>&1
    cp /opt/acuparse/config/acuparse-ssl.conf /etc/apache2/sites-available/ > /dev/null 2>&1
    a2enmod rewrite > /dev/null 2>&1
    a2enmod ssl > /dev/null 2>&1
    a2ensite acuparse.conf > /dev/null 2>&1
    a2ensite acuparse-ssl.conf > /dev/null 2>&1
    sed -i "s/#ServerName/ServerName ${LE_FQDN}\n    ServerAlias www.${LE_FQDN}/g" /etc/apache2/sites-available/acuparse-ssl.conf
    printf "Requesting cert from PRODUCTION server\n"
    certbot -n --authenticator standalone --installer apache --agree-tos --${LE_REDIRECT} --email "${LE_EMAIL}" "${LE_SECURE_DOMAINS[@]}"
    printf "Success\n"
}

printf "\nConfiguring Let's Encrypt\n\n"

printf "Enter FQDN(example.com/hostname.example.com), followed by [ENTER]:\n"
read -r LE_FQDN

printf "Also secure www.$LE_FQDN?, y/N, followed by [ENTER]:\n"
read -r LE_SECURE_WWW

printf "Certificate Email Address, followed by [ENTER]:\n"
read -r LE_EMAIL

printf "Redirect HTTP to HTTPS?, y/N, followed by [ENTER]:\n"
read -r LE_REDIRECT_ENABLED

printf "Deploying Let's Encrypt Certificate\n"
sleep 2
install_le_cert
systemctl restart apache2.service
printf "Done with Certificate Config\n"
exit 0
